sudo: false

language: node_js

node_js:
  - 12.18.1

install:
  - yarn ci
  
script:
  - yarn test
  - yarn start
  
deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master